import type { Metadata } from "next";
import { Geist, Geist_Mono, Fugaz_One, Montserrat } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fugazOne = Fugaz_One({
  subsets: ['latin'],
  weight: '400', 
  variable: '--font-fugaz', 
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: '400', 
  variable: '--font-montserrat', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fugazOne.variable} ${montserrat.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
